---
certificate_environment: staging
discord_webhook: testing

backup:
  repositories:
    local:
      repository_path: /var/backups/restic
      homedir_archive_path: /var/backups/deleted-homedir-archives
    remote:
      provider: gcs
      project_id: grayhaven
      location: US
      storage_class: STANDARD
  schedule: daily
  retention:
    keep_daily: 7
  include:
    - /home
    - /var/log
  exclude: []

observability:
  grafana_cloud:
    enabled: false
    logs_enabled: false

backupctl_repo_url: https://github.com/dean1012/grayhaven-backupctl.git
backupctl_repo_ref: main
backupctl_checkout_dir: /home/ansible/grayhaven-backupctl
