---
certificate:
  environment: staging
  email: admin@example.com
discord_webhook: testing

network:
  vpc_cidr: 10.20.0.0/16

backup:
  repositories:
    local:
      repository_path: /var/backups/restic
      homedir_archive_path: /var/backups/deleted-homedir-archives
    remote:
      provider: gcs
      project_id: grayhaven
      location: US
      storage_class: STANDARD
  schedule: daily
  retention:
    keep_daily: 7
  include:
    - /home
    - /var/log
    - /var/backups/timetracker
  exclude: []

observability:
  grafana_cloud:
    enabled: false
    logs_enabled: false

backupctl_repo_url: https://github.com/dean1012/grayhaven-backupctl.git
backupctl_repo_ref: main
backupctl_checkout_dir: /home/ansible/grayhaven-backupctl

timetracker:
  hostname: timetracker.staging.grayhavensystems.com
  image_digest: sha256:EXAMPLE7a3e5  # 1.2.3-7a3e5
  database_path: /var/lib/timetracker/db/timetracker.db
  backup_artifact_path: /var/backups/timetracker
  backup_retention_days: 7
  branding_repository: https://github.com/dean1012/grayhaven-branding.git
  branding_ref: main
